/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:aebf4960-cd06-4a55-9d2a-bd4552f7db16",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Bl3Z0F4gr",
    "aws_user_pools_web_client_id": "52a5fjdoetd70djpbv4itv3neg",
    "oauth": {
        domain: 'platinumvolunteers.auth.us-east-1.amazoncognito.com',
        redirectSignIn: 'http://platinumvolunteers.com',
        redirectSignOut: 'http://platinumvolunteers.com',
        responeType: 'token'
    },
    "aws_user_files_s3_bucket": "useravatars152459-staging",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "applicationUsers-staging",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "UsersAndEventsApi",
            "endpoint": "https://ejfgcc30xi.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
